package main

import (
	"context"
	"fmt"
	"http-server/config"
	"http-server/handlers"
	"http-server/middleware"
	"http-server/services"
	"http-server/storage"
	"http-server/utils"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"runtime"
	"syscall"
	"time"

	"github.com/go-chi/chi/v5"
	chiMiddleware "github.com/go-chi/chi/v5/middleware"

	_ "http-server/docs" // docs is generated by Swag CLI, you have to import it.

	httpSwagger "github.com/swaggo/http-swagger"
)

// @title Simple HTTP Server API
// @version 1.0
// @description This is a sample server for a simple HTTP server.
// @host localhost:8080
// @BasePath /
func main() {
	// Load configuration
	cfg, err := config.LoadConfig()
	if err != nil {
		panic(fmt.Sprintf("failed to load configuration: %v", err))
	}

	// Initialize logger
	utils.InitLogger(cfg.LogLevel)

	// Initialize database
	db, err := storage.InitDB(&cfg.Database)
	if err != nil {
		utils.Logger.Error("Failed to initialize database", "error", err)
		os.Exit(1)
	}
	defer db.Close()

	// Initialize Redis client
	redisClient, err := storage.NewRedisClient(&cfg.Redis)
	if err != nil {
		utils.Logger.Error("Failed to initialize Redis client", "error", err)
		os.Exit(1)
	}
	defer redisClient.Client.Close()

	// Create user repository, service, and handler
	userRepo := storage.NewUserRepository(db)
	userService := services.NewUserService(userRepo, redisClient)
	userHandler := handlers.NewUserHandler(userService)

	// Create router
	r := chi.NewRouter()

	// ===== Middleware =====
	r.Use(chiMiddleware.RequestID)
	r.Use(middleware.LoggerMiddleware)
	r.Use(middleware.MetricsMiddleware)
	r.Use(chiMiddleware.Recoverer)
	r.Use(middleware.CorsMiddleware())
	r.Use(middleware.RateLimiterMiddleware())
	r.Use(chiMiddleware.AllowContentType("application/json", "text/plain"))
	r.Use(chiMiddleware.Timeout(60 * time.Second))

	// ===== Static files ====
	_, b, _, _ := runtime.Caller(0)
	basepath := filepath.Dir(b)
	staticDir := http.Dir(filepath.Join(basepath, "resources/static"))
	r.Handle("/ui/*", http.StripPrefix("/ui/", http.FileServer(staticDir)))

	// ===== Redirects ====
	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "/ui/", http.StatusFound) // Use http.StatusFound for a temporary redirect (302)
	})

	// ===== Routes =====
	r.Get("/health", handlers.HealthCheckHandler)
	r.Handle("/metrics", handlers.MetricsHandler())

	// Swagger UI
	r.Get("/swagger/*", httpSwagger.Handler(httpSwagger.URL("/swagger/doc.json")))

	r.Route("/users", func(r chi.Router) {
		r.Use(middleware.BasicAuth)
		r.Get("/", userHandler.GetUsersHandler)
		r.Post("/", userHandler.CreateUserHandler)
		r.Get("/{id}", userHandler.GetUserHandler)
		r.Delete("/{id}", userHandler.DeleteUserHandler)
	})

	// Start server
	serverAddr := fmt.Sprintf(":%d", cfg.Server.Port)
	server := &http.Server{Addr: serverAddr, Handler: r}

	// Listen for OS signals to perform a graceful shutdown
	stop := make(chan os.Signal, 1)
	signal.Notify(stop, os.Interrupt, syscall.SIGTERM)

	go func() {
		fmt.Printf("✅ Server running on http://localhost%s\n", serverAddr)
		if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			utils.Logger.Error("Server failed to start", "error", err)
			os.Exit(1)
		}
	}()

	<-stop // Wait for OS signal

	utils.Logger.Info("Shutting down server...")
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if err := server.Shutdown(ctx); err != nil {
		utils.Logger.Error("Server graceful shutdown failed", "error", err)
		os.Exit(1)
	}

	utils.Logger.Info("Server gracefully stopped")
}
